#!/usr/bin/env bash
# Configure Nginx to run as nginx user on port 8080
pkill nginx
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sed -i 's/user www-data/user nginx/' /etc/nginx/nginx.conf
chown -R nginx:nginx /var/log/nginx
nginx
