#!/usr/bin/env bash
pkill nginx
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sed -i 's/user www-data/user nginx/' /etc/nginx/nginx.conf
chown -R nginx:nginx /var/log/nginx
chown -R nginx:nginx /var/lib/nginx
nginx
