#!/usr/bin/env bash
# Start Nginx without using service, and make sure it runs on port 80
apt-get update
apt-get install -y nginx
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
nginx -g 'daemon off;'
