#!/usr/bin/env bash
# Installs and configures Nginx web server

# Update package list
apt-get update -y

# Install nginx
apt-get install nginx -y

# Create a custom index.html with required content
echo "Holberton School for the win!" > /var/www/html/index.html

# Start nginx service
service nginx start

# Enable nginx to start on boot
update-rc.d nginx enable

# Ensure nginx is running
service nginx restart
